"""
test_lob_letter.py — Send ONE test letter via Lob.com to verify setup.

With the test API key the letter is NOT actually mailed — Lob processes it,
returns a preview PDF URL, and charges nothing. Swap to the live key once
you've confirmed the letter looks right.

Usage:
    python test_lob_letter.py

The letter will be sent to Will Workman at the HOA address as a self-test.
Check the printed URL or log into https://dashboard.lob.com to see the PDF preview.
"""

import requests
from datetime import date
from dotenv import load_dotenv
import os

load_dotenv()

LOB_API_KEY  = os.environ.get("LOB_API_KEY", "")
HOA_NAME     = "Signal Butte Ranch HOA"
HOA_LINE1    = "304 South Jones Boulevard #5432"
HOA_CITY     = "Las Vegas"
HOA_STATE    = "NV"
HOA_ZIP      = "89107"
HOA_REMIT    = "P.O. Box 98526, Phoenix, AZ 85038-0526"

# ── Test recipient — sends to you so you can verify the layout ───
TEST_NAME    = "Will Workman"
TEST_LINE1   = "304 South Jones Boulevard #5432"
TEST_CITY    = "Las Vegas"
TEST_STATE   = "NV"
TEST_ZIP     = "89107"

TODAY        = date.today().strftime("%B %d, %Y")
TEST_ACCT    = "99999"
TEST_BALANCE = 372.00

html = f"""<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<style>
  * {{ margin: 0; padding: 0; box-sizing: border-box; }}
  body {{
    font-family: Arial, Helvetica, sans-serif;
    font-size: 11pt;
    line-height: 1.6;
    color: #000;
    width: 8.5in;
    padding: 0.75in;
  }}
  .from-block {{ margin-bottom: 0.35in; font-size: 10pt; color: #333; }}
  .date-block  {{ margin-bottom: 0.3in; }}
  .to-block    {{ margin-bottom: 0.3in; }}
  .re-block    {{ margin-bottom: 0.3in; border-left: 3px solid #000;
                  padding-left: 8px; font-weight: bold; }}
  .body        {{ margin-bottom: 0.3in; }}
  .body p      {{ margin-bottom: 0.15in; }}
  .balance-box {{
    margin-top: 0.25in;
    border: 2px solid #000;
    padding: 8px 14px;
    font-size: 11pt;
    display: inline-block;
  }}
  .remittance {{
    margin-top: 0.4in;
    border: 1px solid #aaa;
    padding: 10px 14px;
    font-size: 10pt;
    background: #f9f9f9;
  }}
  .test-banner {{
    background: #ffffcc;
    border: 2px solid #cc9900;
    padding: 8px;
    text-align: center;
    font-weight: bold;
    margin-bottom: 0.3in;
  }}
</style>
</head>
<body>

<div class="test-banner">⚠️ TEST LETTER — NOT A REAL NOTICE — FOR LAYOUT VERIFICATION ONLY</div>

<div class="from-block">
  <strong>{HOA_NAME}</strong><br>
  {HOA_LINE1}<br>
  {HOA_CITY}, {HOA_STATE} {HOA_ZIP}
</div>

<div class="date-block">{TODAY}</div>

<div class="to-block">
  {TEST_NAME}<br>
  {TEST_LINE1}<br>
  {TEST_CITY}, {TEST_STATE} {TEST_ZIP}
</div>

<div class="re-block">
  RE: Account #{TEST_ACCT} &nbsp;|&nbsp; Outstanding Balance: ${TEST_BALANCE:,.2f}
</div>

<div class="body">
<p>Dear Homeowner,</p>

<p>This is a <strong>test letter</strong> generated by the SBR Collections
Automation system to verify that Lob.com letter sending is correctly configured.</p>

<p>In a real collections run, this page would contain the full body text of
the applicable collections notice (60-Day, 90-Day, Advanced Delinquency, etc.)
pulled from your Buildium letter templates.</p>

<p>If you are reading this letter, the Lob.com integration is working correctly.
The formatting, address placement, and remittance block below are all production-ready.</p>

<p>Sincerely,<br>
Signal Butte Ranch HOA<br>
Board of Directors</p>
</div>

<div class="balance-box">
  <strong>Amount Due: ${TEST_BALANCE:,.2f}</strong>
</div>

<div class="remittance">
  <strong>Remit Payment To:</strong><br>
  {HOA_NAME}<br>
  {HOA_REMIT}<br>
  <em>Please write Account #{TEST_ACCT} on your check or money order.</em>
</div>

</body>
</html>"""

if not LOB_API_KEY:
    print("❌ LOB_API_KEY not found in .env — check your .env file.")
    exit(1)

key_type = "TEST" if LOB_API_KEY.startswith("test_") else "LIVE"
print(f"Using {key_type} Lob API key")
print(f"Sending test letter to: {TEST_NAME}, {TEST_LINE1}, {TEST_CITY}, {TEST_STATE} {TEST_ZIP}")
print("...")

resp = requests.post(
    "https://api.lob.com/v1/letters",
    auth=(LOB_API_KEY, ""),
    data={
        "to[name]":              TEST_NAME,
        "to[address_line1]":     TEST_LINE1,
        "to[address_city]":      TEST_CITY,
        "to[address_state]":     TEST_STATE,
        "to[address_zip]":       TEST_ZIP,
        "to[address_country]":   "US",
        "from[name]":            HOA_NAME,
        "from[address_line1]":   HOA_LINE1,
        "from[address_city]":    HOA_CITY,
        "from[address_state]":   HOA_STATE,
        "from[address_zip]":     HOA_ZIP,
        "from[address_country]": "US",
        "file":                  html,
        "color":                 "false",
        "double_sided":          "false",
        "mail_type":             "usps_first_class",
        "use_type":              "operational",
    },
    timeout=30,
)

if resp.status_code in (200, 201):
    result    = resp.json()
    letter_id = result.get("id", "unknown")
    url       = result.get("url", "")
    status    = result.get("status", "")
    print(f"\n✅ Success!")
    print(f"   Letter ID : {letter_id}")
    print(f"   Status    : {status}")
    if url:
        print(f"   Preview   : {url}")
    print(f"\n{'='*60}")
    print("Next steps:")
    print("  1. Open the Preview URL above to verify the letter layout")
    print("  2. Upload your Word doc letter templates so we can add real body text")
    print("  3. Once layout is confirmed, swap .env to the live_ API key")
    print(f"{'='*60}")
else:
    print(f"\n❌ Lob API error {resp.status_code}:")
    print(resp.text)
